### ISSUE TITLE
System.MissingMethodException: 'Method not found: 'Void BoDi.ObjectContainer.RegisterTypeAs(System.String)'.'

### ISSUE THREAD

**Issue by juanp817** [AdCodicem/SpecFlowMicrosoftDependencyInjection#14]
I have no idea what's happening but I am encounter this error when I run my test scenarios. 
![image](https://user-images.githubusercontent.com/39223172/195497350-a2dbce43-3077-426e-829e-019b2279c0f9.png)

![image](https://user-images.githubusercontent.com/39223172/195496735-86629861-ac3e-44d2-adaa-6d110e771b74.png)

**Comment by AdCodicem** [comment]
Hello @juanp817,
Unfortunately this project is not maintained anymore as you can find everything in  [SpecFlow.DependencyInjection](https://github.com/solidtoken/SpecFlow.DependencyInjection)
