### ISSUE TITLE
Question: Can FeatureContext and ScenarioContext still be injected?

### ISSUE THREAD

**Issue by srigor** [AdCodicem/SpecFlowMicrosoftDependencyInjection#2]
**Disclaimer: This is more of a question than an actual issue.**

Is it possible to use Specflow's context injection solution for step definition classes using this DI plugin? I am needing to still use Specflow's context injection to share some objects between features/scenarios, but I need to also be able to inject other dependencies into the step definition classes from my Startup class in addition to FeatureContext/ScenarioContext.

Thanks for your support and contribution to SpecFlow!

**Comment by AdCodicem** [comment]
Hi @srigor !

It is totally possible to use `ScenarioContext` and `FeatureContext` (and `TestThreadContext` as well) the plugin will inject these services from the original SpecFlow dependency injection.

Thank you for using my plugin !
