### ISSUE TITLE
Question: Can this support singletons?

### ISSUE THREAD

**Issue by StevenDenman** [AdCodicem/SpecFlowMicrosoftDependencyInjection#5]
Is there a way to make the service collection contain singletons so that they are only created once for the whole test run (i.e. scenarios in different features would get the same instance)?

At the moment I have made it so it creates it once and then registers that same instance each time the ConfigureServices is run, but if there was a way to automatically do it then that would be good.

**Comment by AdCodicem** [comment]
Hello Steven,

I'm not sure of what you're trying to achieve, can you send me an example project ?

Thanks !

**Comment by StevenDenman** [comment]
So in my test, I have a test rest client that I use to setup data. Ideally this should just be created _once_ and the same instance reused for each scenario in each feature and between features.

However, ConfigureServices is run per scenario so it cannot be done out of the box?

What I have done is have a lock (so that tests in parallel work properly), check if a static instance of that is null, if it is then create it.
It then sets that same static copy of the rest client in the future calls to ConfigureServices

```
namespace Tests.Hooks
{
    [Binding]
    public class Setup : IServicesConfigurator
    {
        private static TestRestClient? ApiClient = null;
        private static readonly object Lock = new();

        public void ConfigureServices(IServiceCollection services)
        {
            lock (Lock)
            {
                if (ApiClient == null)
                {
                    services.AddKeyVaultConnectionStringProvider(); // adds a dependency that the rest client needs
                    services.AddScoped<TestRestClient>();

                    var provider = services.BuildServiceProvider();
                    ApiClient = provider.GetRequiredService<TestRestClient>();
                }
            }

            services.AddSingleton(ApiClient!);
        }
    }
}
```

**Comment by AdCodicem** [comment]
I think you came with a pretty clean solution :)
I'll see what I can do

**Comment by StevenDenman** [comment]
That solution isn't ideal as in the first run we end up with two TestRestClients registered...

**Comment by StevenDenman** [comment]
I am not sure where you have got with this but this seems a more elegant workaround.
Instead of the horrible lock, I just create the instance in the BeforeTestRun which only gets executed once even in parallel scenarios (assuming you are not using SpecFlow+ Runner).

```
namespace Tests.Hooks
{
    [Binding]
    public class Setup : IServicesConfigurator
    {
        private static TestRestClient? ApiClient = null;
        
        [BeforeTestRun]
        public void CreateGlobals()
        {
            var services = new ServiceCollection();
            services.AddKeyVaultConnectionStringProvider(); // adds a dependency that the rest client needs
            services.AddScoped<TestRestClient>();

            var provider = services.BuildServiceProvider();
            ApiClient = provider.GetRequiredService<TestRestClient>();
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton(ApiClient!);
        }
    }
}
```

**Comment by AdCodicem** [comment]
Hello, 
Unfortunately I didn't find a better solution.
The `[BeforeTestRun]` approach seems good to me !
