### ISSUE TITLE
Bug: DI fails with SpecFlow Bindings from External Assemblies

### ISSUE THREAD

**Issue by StevenDenman** [AdCodicem/SpecFlowMicrosoftDependencyInjection#6]
My test project uses external assemblies for shared steps using the [SpecFlow.json](https://docs.specflow.org/projects/specflow/en/latest/Bindings/Use-Bindings-from-External-Assemblies.html) file.

When this file exists the test fails after ConfigureServices and before the test starts with `System.NullReferenceException: Object reference not set to an instance of an object.`.

It doesn't give much info but as soon as I remove the json file, it works again.

Instead of manually adding just the ScenarioContext, FeatureContext and TestThreadContext, should it just automatically register all types that have the SpecFlow `[Binding]` attribute?

**Comment by StevenDenman** [comment]
```
            var specFlowTypes = System.AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(assembly => assembly.GetTypes())
                .Where(a => System.Attribute.IsDefined(a, typeof(BindingAttribute)));

            foreach (var type in specFlowTypes)
            {
                services.AddScoped(type!);
            }
```

**Comment by AdCodicem** [comment]
Can you provide me a full example project so I can reproduce the bug ?

**Comment by StevenDenman** [comment]
https://github.com/StevenDenman/SpecFlowWithExternalAssemblies

**Comment by StevenDenman** [comment]
If you feel we only need to specifically register steps then maybe check all types that have a Given/When or Then attribute?

**Comment by AdCodicem** [comment]
Hello Steven,
I included your solution directly in the plugin, so it automatically register all the steps :)
Thank you !
