### ISSUE TITLE
Why this plugin? -> SpecFlow.DependencyInjection

### ISSUE THREAD

**Issue by 304NotModified** [AdCodicem/SpecFlowMicrosoftDependencyInjection#8]
Hi,

I'm curious, why this plugin while there is [SpecFlow.DependencyInjection](https://github.com/solidtoken/SpecFlow.DependencyInjection) with the exact same reason? Is that other plugin hard to find or missing some features? 

It's looks a bit funny ([link](https://docs.specflow.org/projects/specflow/en/latest/Extend/Available-Plugins.html))

![image](https://user-images.githubusercontent.com/5808377/157318981-1b703ff7-ebff-4ceb-ae39-401f2ebf94a5.png)

**Comment by AdCodicem** [comment]
Hello,
At the time I created this plugin I needed to inject services injected in the original DI container of SpecFlow (BoDi) like the `ITestOutputHelper` 
I achieved this with the extension method I created in this project `.AddDelegated<T>()`
I may had other motivation at the time but, honestly, I don't remember.
